config/routes.rb
Rails.application.routes.draw do
  resources :notebooks
  get 'site/index'

  get 'sessions/new'

  resources :users
  resources :items
  resources :shelves
  resources :notes
  get "/signup" => "users#new"
  
  get    '/my-library', to: "site#library"
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root "site#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  def get_cover
    require 'RMagick'
    colors = ['#b71c1c','#880E4F','#4A148C','#311B92','#1A237E','#0D47A1','#01579B','#006064','#004D40','#1B5E20','#E65100','#3E2723','#212121','#263238']
    canvas = Magick::Image.new(200, 250){self.background_color = colors.sample}
    gc = Magick::Draw.new
    gc.pointsize(24)
    gc.fill('#fff')
    gc.text(30,70, self.title.center(8))
    
    gc.draw(canvas)
    canvas.write(self.preview)
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
    @notes = Note.where("notebook_id = ?", @notebook.id )
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
    @shelf_options = []
    Shelf.where("user_id = ?", current_user.id).each do |shelf|
      @shelf_options.push([shelf.title, shelf.id])
    end
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)
    @notebook.user_id = current_user.id
    @notebook.preview = File.join(current_user.folder_path, 'previews', @notebook.title+".jpg")
    @notebook.download = File.join(current_user.folder_download, "previews", @notebook.title+".jpg")
    @notebook.get_cover
    respond_to do |format|
      if @notebook.save
        format.html { redirect_to "/my-library", notice: 'Notebook was successfully created.' }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: 'Notebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notebook_params
      params.require(:notebook).permit(:title, :shelf_id)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(notebook) do |f| %>
  <% if notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% notebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Notebook title"%>
    <%= f.text_field :title ,class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :shelf_id, "What shelf should this go on?" %>
  <%= f.select(:shelf_id, options_for_select(@shelf_options), {}, {:class => 'form-control'}) %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn'%>
  </div>
<% end %>
</div>
</div>

app/views/notebooks/edit.html.erb
<h1>Editing Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notebooks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Shelf</th>
      <th>User</th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= notebook.title %></td>
        <td><%= notebook.shelf_id %></td>
        <td><%= notebook.user_id %></td>
        <td><%= notebook.cover %></td>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New Notebook</h1>

<%= render 'form', notebook: @notebook %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <% @notes.each do |note| %>
      <div class="col-sm-2">
          <%= link_to ('<img src="'+note.download+'">').html_safe, note %>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </div>
    <% end %>
</div>
<%= link_to "New Note", new_note_path(:notebook => @notebook.id) %>


<%= link_to 'Edit', edit_notebook_path(@notebook) %> |
<%= link_to 'Back', notebooks_path %>