config/routes.rb
Rails.application.routes.draw do
  resources :notebooks
  get 'site/index'

  get 'sessions/new'

  resources :users
  resources :items
  resources :shelves
  resources :notes
  get "/signup" => "users#new"
  
  get    '/my-library', to: "site#library"
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root "site#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  has_one :user
  def get_preview
    require 'RMagick'
    require 'fileutils'
    FileUtils::mkdir_p File.dirname(self.preview)
    canvas = Magick::Image.new(200, 250){self.background_color = '#FAFAFA'}
    gc = Magick::Draw.new
    gc.pointsize(24)
    gc.fill('#000')
    gc.text(30,70, self.title.center(8))
    gc.pointsize(12)
    gc.text(30,120, self.content.truncate(12).center(8))

    
    gc.draw(canvas)
    canvas.write(self.preview)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
    @notebook_options = []
    Notebook.where("user_id = ?", current_user.id).each do |notebook|
      @notebook_options.push([notebook.title, notebook.id])
    end
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.notebook_id = params[:notebook]
    @note.preview = File.join(current_user.folder_path, "previews", Notebook.find(@note.notebook_id).title, @note.title+".jpg")
    @note.download = File.join(current_user.folder_download, "previews", Notebook.find(@note.notebook_id).title, @note.title+".jpg")
    @note.get_preview
    respond_to do |format|
      if @note.save
        
        format.html { redirect_to "/notebooks/"+@note.notebook_id.to_s, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to "/my-library", notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to "/my-library", notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content, :user_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title ,class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.text_area :content ,class: 'form-control'%>
  </div>
  
  <div class="actions">
  <%= hidden_field_tag(:notebook, params[:notebook]) %>
    <%= f.submit class: "btn" %>
  </div>
<% end %>
</div>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= note.user_id %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>