config/routes.rb
Rails.application.routes.draw do
  resources :notebooks
  get 'site/index'

  get 'sessions/new'

  resources :users
  resources :items
  resources :shelves
  resources :notes
  get "/signup" => "users#new"
  
  get    '/my-library', to: "site#library"
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root "site#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :shelf
  has_one :user
  
  def get_height_ratio(height, width, new_width)
    return (width.to_f/height.to_f) * new_width.to_f
  end
  
  def get_image_preview(width)
    require 'RMagick'
    image = Magick::Image.read(self.file).first
    original_width = image.columns
    original_height = image.rows
    height = get_height_ratio(original_height, original_width, width)
    image.change_geometry!(height.to_s+"x"+width.to_s) { |cols, rows, img|
      newimg = img.resize(cols, rows)
      newimg.write(self.preview_path)
    }
  end
  
  def merge_pdf(file_array)
    # needs revision
      require 'combine_pdf'
      pdf = CombinePDF.new
      file_array.each do |file|
        pdf << CombinePDF.load(file) # one way to combine, very fast.
      end
      pdf.number_pages
      pdf.save self.file
  end
  
  def split_pdf
    require 'combine_pdf'
    pages = CombinePDF.load(self.file).pages;
    i = 0
    pages.each do |page|
       pdf = CombinePDF.new
       pdf << page
       pdf.save("#{i}.pdf")
       i+=1
    end
  end
  
  def image_to_pdf
    require 'rmagick'
    jpg = Magick::ImageList.new(self.file)
    jpg.write(self.file+".jpg")
  end
  
  def get_pdf_preview(width)
    #require 'RMagick'
    #Magick.limit_resource("memory", 20)
    #pdf = Magick::ImageList.new(self.file+"[0]")[0]
    #pdf.resize(width)
    #pdf.background_color = "white"
    #pdf.flatten_images
    #pdf.write(self.preview_path)

    system("convert -alpha off -cache 20 #{self.file}[0] -resize 200 -background white -flatten #{self.preview_path}")
  end
  
  def get_doc_preview(width)
    self.conv_doc_to_pdf
    self.get_pdf_preview(width)
    File.delete(self.file+".pdf")
  end
  
  def conv_doc_to_pdf
    require 'libreconv'
    Libreconv.convert(self.file, self.file+'.pdf')
  end
  

  def get_preview(width)
    require 'fileutils'
    FileUtils::mkdir_p File.dirname(self.preview_path)
    if self.format == "application/pdf"
      self.get_pdf_preview(width)
    elsif self.format == "image/jpeg" || self.format == "image/png"
      self.get_image_preview(width)
    elsif self.format == "application/epub+zip"
      #get preview image of epub
    elsif self.format == "application/x-mobipocket-ebook"
      # get preview image of epub
    elsif self.format == "application/vnd.openxmlformats-officedocument.wordprocessingml.document" || self.format == "application/msword" || self.format == "application/octet-stream"
      self.get_doc_preview(width)
    elsif self.format == "audio/mpeg"
      # get preview image
    elsif self.format == "video/mpeg"
      #get preview image
    else
      # use default image
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @shelf_options = []
    Shelf.where("user_id = ?", current_user.id).each do |shelf|
      @shelf_options.push([shelf.title, shelf.id])
    end
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    require 'fileutils'
    @item = Item.new(item_params)
    uploaded_io = params[:item][:file]
    
    FileUtils::mkdir_p current_user.folder_path
  
    @item.download = File.join(current_user.folder_download,uploaded_io.original_filename)
    @item.file = File.join(current_user.folder_path, uploaded_io.original_filename)
    @item.title = uploaded_io.original_filename
    @item.user_id = current_user.id
    @item.format = uploaded_io.content_type
    @item.shelf_id = params[:item][:shelf_id]
    @item.preview = File.join(current_user.folder_download, "previews", File.basename(@item.title)+".jpg")
    @item.preview_path = File.join(current_user.folder_path, "previews", File.basename(@item.title)+".jpg")
    File.open(@item.file, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @item.get_preview(200)
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to "/my-library", notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to "/my-library", notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to "/my-library", notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:file, :shelf_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="form-group">
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      
      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
      <%= f.label :shelf_id, "What shelf should this go on?" %>
  <%= f.select(:shelf_id, options_for_select(@shelf_options), {}, {:class => 'form-control'}) %>
  <br>
    <%= f.file_field :file ,class: 'form-control'%>
<br>
  <div class="actions">
    <%= f.submit class: 'btn'%>
  </div>
<% end %>
</div>
</div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>